# Generated by Django 3.2.6 on 2022-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
